service: stock-trading-system

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs18.x  
  environment:
    NODE_ENV: dev

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  orderAction:
    handler: app/handler.orderAction
    events:
      - http:
          path: stockOrders
          method: post
  find:
    handler: app/handler.find
    events:
      - http:
          path: stockOrders
          method: get
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: stockOrders/{id}
          method: get
